[package]
name = "rebar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
bio = "1.1.0"
itertools = "0.10.5"
csv = "1.2.1"
reqwest = "0.11.17"
eyre = "0.6.8"
